version: '3'

services:
  redis-master:
    container_name: redis-master
    image: redis:alpine
    volumes: 
      - ./data/:/data
    ports:
      - "6379:6379"
    restart: always

  redis-slave:
    container_name: redis-slave
    build: slave
    links:
      - redis-master
    depends_on:
      - "redis-master"
    ports:
      - "6380:6379"
    restart: always

  redis-sentinel-1:
    container_name: redis-sentinel-1
    build: sentinel
    links:
      - redis-master
    depends_on:
      - "redis-master"
    ports:
      - "6381:6379"
    restart: always

  redis-sentinel-2:
    container_name: redis-sentinel-2
    build: sentinel
    links:
      - redis-master
    depends_on:
      - "redis-master"
    ports:
      - "6382:6379"
    restart: always

  redis-sentinel-3:
    container_name: redis-sentinel-3
    build: sentinel
    links:
      - redis-master
    depends_on:
      - "redis-master"
    ports:
      - "6383:6379"
    restart: always